import dotenv from "dotenv";
dotenv.config({});

const MONGODB_URI_ENV = process.env.MONGODB_URI_ENV;
const JWT_SECRET = process.env.JWT_SECRET;
const FRONTEND_URL = process.env.FRONTEND_URL;
const RESET_EMAIL = process.env.RESET_EMAIL
const TRANSPORTER_EMAIL_USER = process.env.TRANSPORTER_EMAIL_USER
const TRANSPORTER_EMAIL_PASSWORD = process.env.TRANSPORTER_EMAIL_PASSWORD
const DIGITAL_OCEAN_ACCESS_KEY_ID = process.env.DIGITAL_OCEAN_ACCESS_KEY_ID
const DIGITAL_OCEAN_SECRET = process.env.DIGITAL_OCEAN_SECRET
const DIGITAL_OCEAN_ENDPOINT = process.env.DIGITAL_OCEAN_ENDPOINT
const DIGITAL_OCEAN_BUCKET = process.env.DIGITAL_OCEAN_BUCKET
const DIGITAL_OCEAN_REGION = process.env.DIGITAL_OCEAN_REGION

export {
    MONGODB_URI_ENV,
    JWT_SECRET,
    FRONTEND_URL,
    RESET_EMAIL,
    TRANSPORTER_EMAIL_USER,
    TRANSPORTER_EMAIL_PASSWORD,
    DIGITAL_OCEAN_ACCESS_KEY_ID,
    DIGITAL_OCEAN_SECRET,
    DIGITAL_OCEAN_ENDPOINT,
    DIGITAL_OCEAN_BUCKET,
    DIGITAL_OCEAN_REGION
}
